"""sync missing columns

Revision ID: 66821ad98869
Revises: 025
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66821ad98869'
down_revision: Union[str, None] = '025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safety for fresh DBs: create sequence before using it in display_id default.
    op.execute("CREATE SEQUENCE IF NOT EXISTS users_display_id_seq")
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reward_kopecks', sa.Integer(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.drop_index('ix_feedback_user_id', table_name='feedback')
    op.drop_table('feedback')
    op.alter_column('activity_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('case_runs', sa.Column('recovery_of_run_id', sa.UUID(), nullable=True))
    op.alter_column('case_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('cases', sa.Column('ocr_pages', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('ocr_chars', sa.Integer(), nullable=True))
    op.drop_constraint('cases_user_id_fkey', 'cases', type_='foreignkey')
    op.create_foreign_key(None, 'cases', 'users', ['user_id'], ['id'])
    op.alter_column('exemplars', 'edit_distance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invite_codes', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('invite_codes', 'label',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('legal_documents', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('legal_documents', 'created_at')
    op.alter_column('legal_norms', 'article',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('legal_norms', 'paragraph',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('legal_norms', 'content_hash',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='MD5 hash of text for change detection',
               existing_nullable=True)
    op.alter_column('legal_norms', 'edition_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When text was last updated from source',
               existing_nullable=True)
    op.alter_column('legal_norms', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this norm is still in force',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('legal_norms', 'inactive_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Why deactivated (e.g. Утратила силу ФЗ от ...)',
               existing_nullable=True)
    op.drop_index('ix_legal_norms_article', table_name='legal_norms')
    op.drop_index('ix_legal_norms_text_tsvector', table_name='legal_norms', postgresql_using='gin')
    op.create_index('ix_legal_norms_fts', 'legal_norms', ['text_tsvector'], unique=False, postgresql_using='gin')
    op.drop_constraint('legal_norms_document_id_fkey', 'legal_norms', type_='foreignkey')
    op.create_foreign_key(None, 'legal_norms', 'legal_documents', ['document_id'], ['id'])
    op.alter_column('norm_history', 'change_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='updated | deactivated | reactivated | created',
               existing_nullable=False)
    op.alter_column('norm_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('display_id', sa.Integer(), server_default=sa.text("nextval('users_display_id_seq'::regclass)"), nullable=True))
    op.alter_column('users', 'utm_source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_users_nickname', table_name='users')
    op.create_unique_constraint(None, 'users', ['display_id'])
    op.create_unique_constraint(None, 'users', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_nickname', 'users', ['nickname'], unique=True)
    op.alter_column('users', 'utm_source',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('users', 'display_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('norm_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('norm_history', 'change_type',
               existing_type=sa.VARCHAR(length=30),
               comment='updated | deactivated | reactivated | created',
               existing_nullable=False)
    op.drop_constraint(None, 'legal_norms', type_='foreignkey')
    op.create_foreign_key('legal_norms_document_id_fkey', 'legal_norms', 'legal_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_legal_norms_fts', table_name='legal_norms', postgresql_using='gin')
    op.create_index('ix_legal_norms_text_tsvector', 'legal_norms', ['text_tsvector'], unique=False, postgresql_using='gin')
    op.create_index('ix_legal_norms_article', 'legal_norms', ['article'], unique=False)
    op.alter_column('legal_norms', 'inactive_reason',
               existing_type=sa.TEXT(),
               comment='Why deactivated (e.g. Утратила силу ФЗ от ...)',
               existing_nullable=True)
    op.alter_column('legal_norms', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this norm is still in force',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('legal_norms', 'edition_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='When text was last updated from source',
               existing_nullable=True)
    op.alter_column('legal_norms', 'content_hash',
               existing_type=sa.VARCHAR(length=32),
               comment='MD5 hash of text for change detection',
               existing_nullable=True)
    op.alter_column('legal_norms', 'paragraph',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('legal_norms', 'article',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.add_column('legal_documents', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('legal_documents', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('invite_codes', 'label',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invite_codes', 'code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('exemplars', 'edit_distance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_foreign_key('cases_user_id_fkey', 'cases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cases', 'ocr_chars')
    op.drop_column('cases', 'ocr_pages')
    op.alter_column('case_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('case_runs', 'recovery_of_run_id')
    op.alter_column('activity_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=True),
    sa.Column('admin_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reward_kopecks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedback_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_index('ix_feedback_user_id', 'feedback', ['user_id'], unique=False)
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
